#!/usr/bin/python3
import os, sys
sys.path.append("/usr/lib")
import _kipr as k

def open_gate():
    k.set_servo_position(0,220)

def wait_for_light(port):
	while k.analog(port) > 1000:
		k.msleep(100)
		pass
k.enable_servos()
k.set_servo_position(0,220)

open_gate()
wait_for_light(0)
k.shut_down_in(115)
k.set_servo_position(0,2015)	#start zeug

k.msleep(500)
k.motor(0, 100)
k.motor(1, 95)		#fahrt vor
k.msleep(2700)

k.motor(0, 100)
k.motor(1, 100)		#fahrt vor
k.msleep(1800)

k.motor(0, -100)
k.motor(1, -100)	#fahrt kurz zrug
k.msleep(1450)

k.motor(0, 100)
k.motor(1, -30)	#fahrt 90 grad rechts
k.msleep(1000)

count = 0
while True:
    count += 1
    sens_r = int(str(k.analog(4))[:-1] + "0")
    sens_l = int(str(k.analog(2))[:-1] + "0")
    if sens_l == sens_r:
        k.motor(0,100)
        k.motor(1,100)
    elif sens_l > sens_r:
        k.motor(0,100)
        k.motor(1,60)
    elif sens_r > sens_l:
        k.motor(1,100)
        k.motor(0,60)
    k.msleep(10)
    count += 1
    if count >= 2000:
        break
    
k.ao()
